In [1]:
from sklearn import svm
import numpy as np


In [3]:
X_train = np.load("X_train_split_2.dat")
y_train = np.load("y_train_split_2.dat")

In [4]:
from sklearn.utils import shuffle
X_train, y_train = shuffle(X_train, y_train)

In [5]:
X_train = X_train/255

print(X_train.shape)
print(y_train.shape)
X_train_size = len(X_train)
print(X_train_size)

# This reduces dimensionality by 1 (i.e. 3d to 2d)
X_train = X_train.reshape(X_train_size, -1)
y_train = y_train.reshape(-1, 1)
y_train = np.ravel(y_train)
print(X_train.shape)
print(y_train.shape)

(13500, 124, 174)
(13500, 10)
13500
(13500, 21576)
(135000,)


In [7]:
training_set_size = int(X_train.shape[0] * .80)

# split data into validation set
X_train_validation = X_train[training_set_size:, :]
y_train_validation = y_train[training_set_size:]
y_train = y_train[:training_set_size]
X_train = X_train[:training_set_size, :]
print("Validation x train set:" + str(X_train_validation.shape))
print("X train set:" + str(X_train.shape))
print("Validation y train set:" + str(y_train_validation.shape))
print("Y train set:" + str(y_train.shape))

Validation x train set:(2700, 21576)
X train set:(10800, 21576)
Validation y train set:(124200,)
Y train set:(10800,)


In [ ]:
# X = X_train, Y = y_train
clf = svm.SVC(gamma=0.001)
clf.fit(X_train, y_train)
predictions = clf.predict(X_train_validation)
print(predictions)

[[0.00392157 0.         0.         ... 0.75686275 0.94509804 0.8627451 ]
 [0.         0.         0.         ... 0.41176471 0.49019608 0.5254902 ]
 [0.23137255 0.3372549  0.42352941 ... 0.92156863 0.94509804 0.92156863]
 ...
 [0.         0.         0.         ... 0.78039216 0.88235294 0.84705882]
 [0.04313725 0.         0.         ... 0.74117647 0.59607843 0.73333333]
 [0.08627451 0.01568627 0.04705882 ... 0.72156863 0.56862745 0.72156863]]
[0 0 0 ... 0 0 0]
